---
semodule_te_items:
  - files/nodepool/opt/ansible-role-semodule/ansible_nginx.te

logrotate_configs:
  - name: nodepool
    log: /var/log/nodepool/*.log
    options:
      - compress
      - missingok
      - rotate 7
      - daily
      - notifempty

diskimage_builder_install_method: pkg

nodepool_config_gearman_servers:
  - host: "{{ hostvars.zuul.ansible_ssh_host }}"
    port: 4730

nodepool_config_zmq_publishers:
  - tcp://{{ hostvars.jenkins01.ansible_ssh_host }}:8888
  - tcp://{{ hostvars.jenkins02.ansible_ssh_host }}:8888

nodepool_elements_dir: /home/pabelanger/git/pabelanger/config/nodepool/elements/
nodepool_scripts_dir: /home/pabelanger/git/pabelanger/config/nodepool/scripts/

nodepool_template_nodepool_yaml_contents: "{{ lookup('file', '/home/pabelanger/git/pabelanger/config/nodepool/nodepool.yaml') }}"

nginx_config_include_files: files/nodepool/etc/nginx/conf.d/

ssh_user_name: nodepool
ssh_user_home: /var/lib/nodepool
ssh_key_public_content: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCmRis9o4HCoVNZB0tzDUBWU+t/N15PeZ2X7/NVz4J0C1BXA8eNUZtRTpx0hP6kiPpR5DeLTMyo5GzgDPR1+o8ZsTarmZfxYlxpImaPl3WGEkR3jX0zS2eris6nI6c5BthkInwNYPpW6L5K3F6OaC45U6guxAEszzmH3mKI5nhVgWnxOjyUzqJ3PjOKoH7ClrSa2L3YaOa3N3swoplux3zRCwA55b5fAdRE0aBKlHBpsOFeuGINKXFpONpB2GHMa8mYBOmOi9g4vi+nRyuxcD9TiRfcfiVH9dlMxI9nAnTJwPJLyaRKfewT5N33lK9oYVbtYvNeSapLcyZQETAk6hvW1nhuqYuKnlB8sRdueeWeZTDzGbUq8sKoovv83ZOr7bvL3EWrdeem8fAMxA8gqJgKPXe5Dy7DxFY0+3J7yKUgrMwEqFP9kM1t54sIYWTyJS8wL4WzS+UjMFj1YyX5rN9UcCTjT5iiWfcTLUGqm0nVMQ2Z9wowgq87itjq+T90IbHNwljfKhIQG+DYhq1mI89PGx2ZlS+PM/R8Q6CB7X0fc8FFVeIpwolN6RK2JA60uQBLvZ8AkiRc0YXLFeugmvzsJA3RpHuIteYEADQWhOqbOKElDDcmAlgzs1JBZlqZtfoLIHot/wwvbkVRyokLZ3D1uF9Hs5qQqTR1D1hUWKXjgQ== nodepool@example.org

sudoers_file_includes_src: files/nodepool/etc/sudoers.d/
